### ISSUE TITLE
Unable to run npm install

### ISSUE THREAD

**Issue by prtksxna** [winkjs/wink-regression-tree#15]
I am using node `v8.9.4` and npm `v5.6.0`. On a fresh clone of the `wink-regression-tree` when I run `npm install` I get the following error:

```
▶ npm install
npm ERR! code E404
npm ERR! 404 Not Found: har-validator@https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz
```

And this is the end of the debug.log:

```
3946 verbose type Error
3947 verbose stack Error: 404 Not Found: har-validator@https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz
3947 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
3947 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
3947 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
3947 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
3947 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
3947 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
3947 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
3947 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
3947 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
3947 verbose stack     at runCallback (timers.js:789:20)
3947 verbose stack     at tryOnImmediate (timers.js:751:5)
3947 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
3948 verbose cwd /Users/psaxena/work/wink-regression-tree
3949 verbose Darwin 16.7.0
3950 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
3951 verbose node v8.9.4
3952 verbose npm  v5.6.0
3953 error code E404
3954 error 404 Not Found: har-validator@https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz
3955 verbose exit [ 1, true ]
```

**Comment by prtksxna** [comment]
Possibly related to https://github.com/ahmadnassri/node-har-validator/issues/113

**Comment by prtksxna** [comment]
Removing the `package-lock.json` file and running `npm install` solves the issue.
